/**:
  # general parameters shared by all vesc-related nodes         //所有VESC相关节点共享参数
  ros__parameters:
    # erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
    speed_to_erpm_gain: 4614.0                                  #把Ackermann速度指令换算成VESC期望的电机电气转速(ERPM)
    speed_to_erpm_offset: 0.0

    # servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
    steering_angle_to_servo_gain: -1.2135                       #把Ackermann转角转换成伺服占空比(0～1)
    steering_angle_to_servo_offset: 0.5304                      #方向盘居中时基准占空比

    port: /dev/sensors/vesc                                     #VESC串口路径
    duty_cycle_min: 0.0                                         
    duty_cycle_max: 0.0
    current_min: 0.0
    current_max: 100.0
    brake_min: -20000.0                                         
    brake_max: 200000.0
    speed_min: -23250.0
    speed_max: 23250.0
    position_min: 0.0
    position_max: 0.0
    servo_min: 0.10                                              #舵机占空比下限
    servo_max: 0.95                                              #舵机占空比上限

# No longer needed, all parameters are shared
# ackermann_to_vesc_node:
#   ros__parameters:

vesc_to_odom_node:                                               #里程计坐标系
  ros__parameters:                                      
    odom_frame: odom                                             #里程计和TF发布中的世界坐标系名称
    base_frame: base_link                                        #车辆本体坐标系名称
    # publish odom to base link tf
    publish_tf: true                                             #决定是否由该节点发布TF
    use_servo_cmd_to_calc_angular_velocity: true                 
    # car wheelbase is about 25cm
    wheelbase: .25                                               #车辆轴距，用于从转向角和线速度推导角速度

# No longer needed, all parameters are shared
# vesc_driver:
#   ros__parameters:

throttle_interpolator:                                            #用于油门/舵机平滑(没啥用)
  ros__parameters:
    rpm_input_topic: commands/motor/unsmoothed_speed
    rpm_output_topic: commands/motor/speed
    servo_input_topic: commands/servo/unsmoothed_position
    servo_output_topic: commands/servo/position

    # servo smoother - limits acceleration and smooths anything above limit
    max_acceleration: 2.5 # meters/second^2
    throttle_smoother_rate: 75.0 # messages/sec
    # servo smoother - limits rotation speed and smooths anything above limit
    max_servo_speed: 3.2 # radians/second
    servo_smoother_rate: 75.0 # messages/sec